
//Municipal List
var munilist = Array();
munilist[0]="Benji"
munilist[1]="Alachua";
munilist[2]="Alford";
munilist[3]="Altamonte Springs";
munilist[4]="Anna Maria";
munilist[5]="Apalachicola";
munilist[6]="Apopka";
munilist[7]="Arcadia"; 
munilist[8]="Archer";
munilist[9]="Astatula";
munilist[10]="Atlantic Beach";
munilist[11]="Atlantis";
munilist[12]="Auburndale";
munilist[13]="Aventura";
munilist[14]="Avon Park";
munilist[15]="Bal Harbour";
munilist[16]="Baldwin";
munilist[17]="Bartow"; 
munilist[18]="Bascom";
munilist[19]="Bay Harbor Islands";
munilist[20]="Bell";
munilist[21]="Belle Glade";
munilist[22]="Belle Isle";
munilist[23]="Belleair";
munilist[24]="Belleair Bluffs";
munilist[25]="Belleair Shore";
munilist[26]="Beverly Beach";
munilist[27]="Biscayne Park";
munilist[28]="Boca Raton";
munilist[29]="Bonita Springs";
munilist[30]="Bowling Green";
munilist[31]="Boynton Beach";
munilist[32]="Bradenton Beach";
munilist[33]="Bradenton";
munilist[34]="Branford";
munilist[35]="Briny Breezes";
munilist[36]="Bristol"; 
munilist[37]="Bronson";
munilist[38]="Brooker";
munilist[39]="Brooksville"; 
munilist[40]="Bushnell";
munilist[41]="Callahan";
munilist[42]="Callaway";
munilist[43]="Campbellton";
munilist[44]="Cape Canaveral";
munilist[45]="Cape Coral";
munilist[46]="Carrabelle";
munilist[47]="Caryville";
munilist[48]="Casselberry";
munilist[49]="Cedar Key";
munilist[50]="Center Hill";
munilist[51]="Century";
munilist[52]="Chattahoochee";
munilist[53]="Chiefland";
munilist[54]="Chipley";
munilist[55]="Cinco Bayou";
munilist[56]="Clearwater"; 
munilist[57]="Clermont";
munilist[58]="Clewiston";
munilist[59]="Cloud Lake";
munilist[60]="Cocoa";
munilist[61]="Cocoa Beach";
munilist[62]="Coconut Creek";
munilist[63]="Coleman";
munilist[64]="Cooper City";
munilist[65]="Coral Gables";
munilist[66]="Coral Springs";
munilist[67]="Cottondale";
munilist[68]="Crescent City";
munilist[69]="Crestview";
munilist[70]="Cross City"; 
munilist[71]="Crystal River";
munilist[72]="Cutler Bay";
munilist[73]="Dade City ";
munilist[74]="Dania Beach";
munilist[75]="Davenport";
munilist[76]="Davie";
munilist[77]="Daytona Beach";
munilist[78]="Daytona Beach Shores";
munilist[79]="DeBary";
munilist[80]="Deerfield Beach";
munilist[81]="DeFuniak Springs ";
munilist[82]="DeLand ";
munilist[83]="Delray Beach";
munilist[84]="Deltona";
munilist[85]="Destin";
munilist[86]="Doral";
munilist[87]="Dundee";
munilist[88]="Dunedin";
munilist[89]="Dunnellon";
munilist[90]="Eagle Lake";
munilist[91]="Eatonville";
munilist[92]="Ebro";
munilist[93]="Edgewater";
munilist[94]="Edgewood";
munilist[95]="El Portal";
munilist[96]="Esto";
munilist[97]="Eustis";
munilist[98]="Everglades City";
munilist[99]="Fanning Springs";
munilist[100]="Fellsmere";
munilist[101]="Fernandina Beach ";
munilist[102]="Flagler Beach";
munilist[103]="Florida City";
munilist[104]="Fort Lauderdale ";
munilist[105]="Fort Meade";
munilist[106]="Fort Myers Beach";
munilist[107]="Fort Myers ";
munilist[108]="Fort Pierce ";
munilist[109]="Fort Walton Beach";
munilist[110]="Fort White";
munilist[111]="Freeport";
munilist[112]="Frostproof";
munilist[113]="Fruitland Park";
munilist[114]="Gainesville ";
munilist[115]="Glen Ridge";
munilist[116]="Glen St. Mary";
munilist[117]="Golden Beach";
munilist[118]="Golf";
munilist[119]="Graceville";
munilist[120]="Grand Ridge";
munilist[121]="Grant-Valkaria";
munilist[122]="Green Cove Springs"; 
munilist[123]="Greenacres";
munilist[124]="Greensboro";
munilist[125]="Greenville";
munilist[126]="Greenwood";
munilist[127]="Gretna";
munilist[128]="Groveland";
munilist[129]="Gulf Breeze";
munilist[130]="Gulf Stream";
munilist[131]="Gulfport";
munilist[132]="Haines City";
munilist[133]="Hallandale Beach";
munilist[134]="Hampton";
munilist[135]="Hastings";
munilist[136]="Havana";
munilist[137]="Haverhill";
munilist[138]="Hawthorne";
munilist[139]="Hialeah";
munilist[140]="Hialeah Gardens";
munilist[141]="High Springs";
munilist[142]="Highland Beach";
munilist[143]="Highland Park";
munilist[144]="Hillcrest Heights";
munilist[145]="Hilliard";
munilist[146]="Hillsboro Beach";
munilist[147]="Holly Hill";
munilist[148]="Hollywood";
munilist[149]="Holmes Beach";
munilist[150]="Homestead";
munilist[151]="Horseshoe Beach";
munilist[152]="Howey-in-the-Hills";
munilist[153]="Hypoluxo";
munilist[154]="Indialantic";
munilist[155]="Indian Creek";
munilist[156]="Indian Harbour Beach";
munilist[157]="Indian River Shores";
munilist[158]="Indian Rocks Beach";
munilist[159]="Indian Shores";
munilist[160]="Inglis";
munilist[161]="Interlachen";
munilist[162]="Inverness ";
munilist[163]="Islamorada";
munilist[164]="Jacksonville Beach";
munilist[165]="Jacksonville"; 
munilist[166]="Jacob City";
munilist[167]="Jasper"; 
munilist[168]="Jay";
munilist[169]="Jennings";
munilist[170]="Juno Beach";
munilist[171]="Jupiter";
munilist[172]="Jupiter Inlet Colony";
munilist[173]="Jupiter Island";
munilist[174]="Kenneth City";
munilist[175]="Key Biscayne";
munilist[176]="Key Colony Beach";
munilist[177]="Key West ";
munilist[178]="Keystone Heights";
munilist[179]="Kissimmee ";
munilist[180]="LaBelle ";
munilist[181]="LaCrosse";
munilist[182]="Lady Lake";
munilist[183]="Lake Alfred";
munilist[184]="Lake Buena Vista";
munilist[185]="Lake Butler ";
munilist[186]="Lake City ";
munilist[187]="Lake Clarke Shores";
munilist[188]="Lake Hamilton";
munilist[189]="Lake Helen";
munilist[190]="Lake Mary";
munilist[191]="Lake Park";
munilist[192]="Lake Placid";
munilist[193]="Lake Wales";
munilist[194]="Lake Worth";
munilist[195]="Lakeland";
munilist[196]="Lantana";
munilist[197]="Largo";
munilist[198]="Lauderdale Lakes";
munilist[199]="Lauderdale-by-the-Sea";
munilist[200]="Lauderhill";
munilist[201]="Laurel Hill";
munilist[202]="Lawtey";
munilist[203]="Layton";
munilist[204]="Lazy Lake";
munilist[205]="Lee";
munilist[206]="Leesburg";
munilist[207]="Lighthouse Point";
munilist[208]="Live Oak ";
munilist[209]="Longboat Key";
munilist[210]="Longwood";
munilist[211]="Loxahatchee Groves";
munilist[212]="Lynn Haven";
munilist[213]="Macclenny ";
munilist[214]="Madeira Beach";
munilist[215]="Madison ";
munilist[216]="Maitland";
munilist[217]="Malabar";
munilist[218]="Malone";
munilist[219]="Manalapan";
munilist[220]="Mangonia Park";
munilist[221]="Marathon";
munilist[222]="Marco Island";
munilist[223]="Margate";
munilist[224]="Marianna ";
munilist[225]="Marineland";
munilist[226]="Mary Esther";
munilist[227]="Mascotte";
munilist[228]="Mayo ";
munilist[229]="McIntosh";
munilist[230]="Medley";
munilist[231]="Melbourne";
munilist[232]="Melbourne Beach";
munilist[233]="Melbourne Village";
munilist[234]="Mexico Beach";
munilist[235]="Miami Beach";
munilist[236]="Miami Gardens";
munilist[237]="Miami Lakes";
munilist[238]="Miami Shores";
munilist[239]="Miami Springs";
munilist[240]="Miami ";
munilist[241]="Micanopy";
munilist[242]="Midway";
munilist[243]="Milton ";
munilist[244]="Minneola";
munilist[245]="Miramar";
munilist[246]="Monticello ";
munilist[247]="Montverde";
munilist[248]="Moore Haven ";
munilist[249]="Mount Dora";
munilist[250]="Mulberry";
munilist[251]="Naples ";
munilist[252]="Neptune Beach";
munilist[253]="New Port Richey";
munilist[254]="New Smyrna Beach";
munilist[255]="Newberry";
munilist[256]="Niceville";
munilist[257]="Noma";
munilist[258]="North Bay Village";
munilist[259]="North Lauderdale";
munilist[260]="North Miami";
munilist[261]="North Miami Beach";
munilist[262]="North Palm Beach";
munilist[263]="North Port";
munilist[264]="North Redington Beach";
munilist[265]="Oak Hill";
munilist[266]="Oakland";
munilist[267]="Oakland Park";
munilist[268]="Ocala ";
munilist[269]="Ocean Breeze";
munilist[270]="Ocean Ridge";
munilist[271]="Ocoee";
munilist[272]="Okeechobee"; 
munilist[273]="Oldsmar";
munilist[274]="Opa-locka";
munilist[275]="Orange City";
munilist[276]="Orange Park";
munilist[277]="Orchid";
munilist[278]="Orlando ";
munilist[279]="Ormond Beach";
munilist[280]="Otter Creek";
munilist[281]="Oviedo";
munilist[282]="Pahokee";
munilist[283]="Palatka ";
munilist[284]="Palm Bay";
munilist[285]="Palm Beach";
munilist[286]="Palm Beach Gardens";
munilist[287]="Palm Beach Shores";
munilist[288]="Palm Coast";
munilist[289]="Palm Shores";
munilist[290]="Palm Springs";
munilist[291]="Palmetto";
munilist[292]="Palmetto Bay";
munilist[293]="Panama City Beach";
munilist[294]="Panama City ";
munilist[295]="Parker";
munilist[296]="Parkland";
munilist[297]="Paxton";
munilist[298]="Pembroke Park";
munilist[299]="Pembroke Pines";
munilist[300]="Penney Farms";
munilist[301]="Pensacola ";
munilist[302]="Perry ";
munilist[303]="Pierson";
munilist[304]="Pinecrest";
munilist[305]="Pinellas Park";
munilist[306]="Plant City";
munilist[307]="Plantation";
munilist[308]="Polk City";
munilist[309]="Pomona Park";
munilist[310]="Pompano Beach";
munilist[311]="Ponce de Leon";
munilist[312]="Ponce Inlet";
munilist[313]="Port Orange";
munilist[314]="Port Richey";
munilist[315]="Port St. Joe ";
munilist[316]="Port St. Lucie";
munilist[317]="Punta Gorda ";
munilist[318]="Quincy ";
munilist[319]="Raiford";
munilist[320]="Reddick";
munilist[321]="Redington Beach";
munilist[322]="Redington Shores";
munilist[323]="Riviera Beach";
munilist[324]="Rockledge";
munilist[325]="Royal Palm Beach";
munilist[326]="Safety Harbor";
munilist[327]="San Antonio";
munilist[328]="Sanford ";
munilist[329]="Sanibel";
munilist[330]="Sarasota ";
munilist[331]="Satellite Beach";
munilist[332]="Sea Ranch Lakes";
munilist[333]="Sebastian";
munilist[334]="Sebring ";
munilist[335]="Seminole";
munilist[336]="Sewall's Point";
munilist[337]="Shalimar";
munilist[338]="Sneads";
munilist[339]="Sopchoppy";
munilist[340]="South Bay";
munilist[341]="South Daytona";
munilist[342]="South Miami";
munilist[343]="South Palm Beach";
munilist[344]="South Pasadena";
munilist[345]="Southwest Ranches";
munilist[346]="Springfield";
munilist[347]="St. Augustine Beach";
munilist[348]="St. Augustine ";
munilist[349]="St. Cloud";
munilist[350]="St. Leo";
munilist[351]="St. Lucie Village";
munilist[352]="St. Marks";
munilist[353]="St. Pete Beach";
munilist[354]="St. Petersburg";
munilist[355]="Starke ";
munilist[356]="Stuart ";
munilist[357]="Sunny Isles Beach";
munilist[358]="Sunrise";
munilist[359]="Surfside";
munilist[360]="Sweetwater";
munilist[361]="Tallahassee ";
munilist[362]="Tamarac";
munilist[363]="Tampa ";
munilist[364]="Tarpon Springs";
munilist[365]="Tavares ";
munilist[366]="Temple Terrace";
munilist[367]="Tequesta";
munilist[368]="Titusville"; 
munilist[369]="Treasure Island";
munilist[370]="Trenton ";
munilist[371]="Umatilla";
munilist[372]="Valparaiso";
munilist[373]="Venice";
munilist[374]="Vernon";
munilist[375]="Vero Beach ";
munilist[376]="Virginia Gardens";
munilist[377]="Waldo";
munilist[378]="Wauchula"; 
munilist[379]="Wausau";
munilist[380]="Webster";
munilist[381]="Weeki Wachee";
munilist[382]="Welaka";
munilist[383]="Wellington";
munilist[384]="West Melbourne";
munilist[385]="West Miami";
munilist[386]="West Palm Beach"; 
munilist[387]="West Park";
munilist[388]="Weston";
munilist[389]="Westville";
munilist[390]="Wewahitchka";
munilist[391]="White Springs";
munilist[392]="Wildwood";
munilist[393]="Williston";
munilist[394]="Wilton Manors";
munilist[395]="Windermere";
munilist[396]="Winter Garden";
munilist[397]="Winter Haven";
munilist[398]="Winter Park";
munilist[399]="Winter Springs";
munilist[400]="Worthington Springs";
munilist[401]="Yankeetown";
munilist[402]="Zephyrhills";
munilist[403]="Zolfo Springs";

CreateList();

//Display List of Municipalities
function CreateList(){
	var munis=document.getElementById("munilist");
	for (var i = 1; i < 404; i++) {
		munis.innerHTML += "<div id='" + munilist[i] + "' class='munihidden'><span id='munilink'>" + munilist[i] + "</span></div>";
	};
}

//Open Municipality Panel
//Must get individual id
$(".munihidden").click(function(){

	//grab id
	var id = this.id;

	//toggle hidden and shown
	$("[id='"+id+"']").toggleClass("munihidden");
	$("[id='"+id+"']").toggleClass("munishown");
	$("#mainmuni").html(id);
	
	if (this.className == "munishown"){
		fillDiv(id);
	}
	else if (this.className == "munihidden"){
		emptyDiv(id);
	}
});


function fillDiv(id) {
	var circleNum;
	var circleString;
	var muniBoxString = '';

	muniBoxString += "<div class='muniname'>" + id + "</div>";
	muniBoxString += "<div class='department' id='department1'>City Hall</div><div class='icon' id='icon1'><img src='./img/cityhall.jpg'></div>";
	muniBoxString += "<div class='department' id='department2'>Police Station</div><div class='icon' id='icon2'><img src='./img/badge.jpg'></div>";
	muniBoxString += "<div class='department' id='department3'>Boring Office Building</div><div class='icon' id='icon3'><img src='./img/office.jpg'></div>";
	muniBoxString += "<div class='department' id='department4'>Oh No There's a Fire</div><div class='icon' id='icon4'><img src='./img/hydrant.jpg'></div>";

	//add overall circles
	for (circleNum = 1; circleNum <= 5; circleNum++){ 	//id for each circle is "circle1", "circle2", etc
	muniBoxString += "<div class='department' id='department1'>City Hall</div>";
	muniBoxString += "<div class='department' id='department2'>Police Station</div>";
	muniBoxString += "<div class='department' id='department3'>Office Building</div>";
	muniBoxString += "<div class='department' id='department4'>Office Building</div>";
}

	//add overall circles
	for (circleNum = 1; circleNum <= 4; circleNum++){ 	//id for each circle is "circle1", "circle2", etc
		circleString = "<div class='circle' id='circle" + circleNum + "'><div class='score' id='score" + circleNum + "'>86</div><embed src='circle.svg' height='100%'></div></div>";
		muniBoxString += circleString;
	}

	$("[id='"+id+"']").html(muniBoxString);
}

function emptyDiv(id) {
	$("[id='"+id+"']").html("<span id='munilink'>" + id + "</span>");
}
